version: '3.9'
services:
  nelp:
    build:
      context: .
    volumes:
      - ./packages:/nelp/packages
      - catalog-uploads:/nelp/packages/core/uploads
      - /nelp/node_modules
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nelp
      - POSTGRES_PASSWORD=nelp
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nelp.app.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nelp
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: 'redis:alpine'
    command: ['redis-server', '--appendonly yes']
    volumes:
      - redis:/data
  nginx:
    image: 'nginx:1-alpine'
    ports:
      - 3737:3737
      - 8000:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/cert.crt:/etc/nginx/ssl/cert.crt
      - ./config/private.key:/etc/nginx/ssl/private.key
      - catalog-uploads:/etc/nginx/uploads
    depends_on:
      - nelp
volumes:
  catalog-uploads:
  pgadmin:
  postgres:
  redis:
  fa-config:
