version: '3.9'
services:
  nelp:
    build:
      context: .
      # target: test
    volumes:
      - ./packages:/nelp/packages
      - node_modules:/nelp/node_modules
  redis:
    image: 'redis:alpine'
    command: ['redis-server', '--appendonly yes']
    volumes:
      - redis-data:/data
  postgres:
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=nelp
      - POSTGRES_PASSWORD=nelp_pg_3718
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    image: 'nginx:1-alpine'
    ports:
      - 3737:3737
      - 8000:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/shared.conf:/etc/nginx/includes/shared.conf
      - ./config/cert.crt:/etc/nginx/ssl/cert.crt
      - ./config/private.key:/etc/nginx/ssl/private.key
      - catalog-uploads:/etc/nginx/uploads
    depends_on:
      - nelp
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
volumes:
  redis-data:
  postgres-data:
  catalog-uploads:
  pgadmin-data:
    driver: local
  node_modules:
