version: '3.9'
services:
  # nelp:
  #   build:
  #     context: .
  #   volumes:
  #     - ./packages:/nelp/packages
  #     - /nelp/node_modules
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nelp
      - POSTGRES_PASSWORD=nelp
  redis:
    image: 'redis:alpine'
    command: ['redis-server', '--appendonly yes']
    volumes:
      - ./data/redis:/data
  # nginx:
  #   image: 'nginx:1-alpine'
  #   ports:
  #     - 3737:3737
  #     - 8000:8000
  #     - 8001:8001
  #     - 8002:8002
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf
  #     - ./config/cert.crt:/etc/nginx/ssl/cert.crt
  #     - ./config/private.key:/etc/nginx/ssl/private.key
  #     - ./data/catalog-uploads:/etc/nginx/uploads
  #   depends_on:
  #     - nelp
